# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6173ccef402f1987f4a0546a1a9eb67bc932d3ccc94acdbd96c38de1160374a186fd0358c3189996181128f132c96ef7ca1c0ffe5c478e0f6d405814e2c6ef70

test:
  secret_key_base: bff54a34ecdc82c5c2ef1c13bdea2b197737582b2a88703759ffb21a623c9de8a97b41365576d7b002bf3cd1d78242dae9af9edde4f80a30bf917c86cf5b430a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
